server:
  port: 8083
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
    jackson:
      default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
env: dev
